### ISSUE TITLE
v0.29 beta4 - Stage Clear Bonus disproportionately small

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#52]
As of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a, I cleared Stage 2 with 40 million points, and the stage clear bonus was 2 million. Perhaps boost that number to be a higher?

**Comment by Sparen** [comment]
Note: A single spell card bonus can be up to 5 or so times higher than the stage clear bonus

**Comment by ExPorygon** [comment]
A reminder that while spellcard captures are often worth millions of points, in ALL of ZUN's recent games the stage clear bonus has always been that stage number *1,000,000. That said, I will consider changing this to be more significant.

**Comment by Kappatalist** [comment]
The stage clear bonus as it is right now, regardless of size, is pretty pointless, since afaik it is completely static. There is plenty of room to make it dynamic, such as no-miss bonus, no-miss-no-bomb bonus, points for # items collected (what about a bonus for the # of "discord full" items?), scaling by difficulty level, etc. In addition, these rewards could snowball (for example, # items rolls over between stages as long as you don't die, No-Miss bonus doubles every consecutive time it is awarded, so on.) It can be so much more than "here, you beat the stage, here's a trophy".
